OBJS:=boot.o kernel.o
 
CRTI_OBJ=crti.o
CFLAGS=-std=gnu99 -ffreestanding -O2 -Wall -Wextra
LFLAGS=-ffreestanding -O2 -nostdlib -lgcc -T
CRTBEGIN_OBJ:=$(shell $(CC) $(LFLAGS) -print-file-name=crtbegin.o)
CRTEND_OBJ:=$(shell $(CC) $(LFLAGS) -print-file-name=crtend.o)
CRTN_OBJ=crtn.o
 
OBJ_LINK_LIST:=$(CRTI_OBJ) $(CRTBEGIN_OBJ) $(OBJS) $(CRTEND_OBJ) $(CRTN_OBJ)
INTERNAL_OBJS:=$(CRTI_OBJ) $(OBJS) $(CRTN_OBJ)
 
kernel.o:
	$(CC) -o kernel.o $(CFLAGS) 

myos.bin: $(OBJ_LINK_LIST)
	$(CC) -o myos.bin $(OBJ_LINK_LIST)
 
clean:
	rm -f myos.kernel $(INTERNAL_OBJS)